<?php

"SELECT T_ADHERENTS.NOM,T_MESSAGES.message
FROM T_ADHERENTS,T_MESSAGES 
WHERE T_ADHERENTS.id=T_MESSAGES.id_adherent
    AND T_ADHERENTS.nom ='Machin'";

"SELECT T-ADHERENTS.nom, T_MESSAGES.text
FROM T_ADHERENTS
INNER JOIN T_MESSAGE ON T_ADHERENTS.id=T_MESSAGE.id_adherent
WHERE T-ADHERENTS.nom ='Michel'";